### ISSUE TITLE
Build for iOS fails

### ISSUE THREAD

**Issue by thinklog** [efortuna/memechat#22]
build for iOS fails, complaining that it cannot perform CopyPlistFile with command line argument <UpperLevelFolders>/memechat/build/ios/Release-iphonesimulator/Runner.app/GoogleService-Info.plist Runner/GoogleService-Info.plist
In fact, if you look in package Runner.app located at Release-iphonesimulator/Runner.app you will find the files
app.flx
AppFrameworkInfo.plist
Debug.xcconfig
Generated.xcconfig
Runner
There is no file path GoogleService-Info.plist Runner/GoogleService-Info.plist in Runner.app

How to fix this?

Thanks.
P.S. Building the Flutter gallery demo for iOS succeeds with no problems.

**Comment by emshack** [comment]
If I understand correctly, it sounds like you don't have a GoogleService-Info.plist file. In order to successfully run memechat, you'll need to go through the steps outlined in the readme. This involves creating a Firebase instance, and copying its GoogleService-Info.plist file into your local checkout of memechat. The Flutter gallery demo isn't integrated with Firebase, so this step isn't necessary. Let us know if going through the memechat readme steps resolves your issue!

**Comment by thinklog** [comment]
Thanks for the prompt reply. Will do.

**Comment by emshack** [comment]
Going to go ahead and close this, feel free to reopen if something isn't working.

**Comment by viju85** [comment]
I still get an error when building iOS even when I have the GoogleService-Info.plist under memechat/ios/Runner/

[Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure] to your application initialization. Read more: https://goo.gl/ctyzm8.
[Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
